apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: demo-app-chatbot 
  janus-idp.io/tekton: demo-app-chatbot
  backstage.io/kubernetes-id: demo-app-chatbot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: demo-app-chatbot
resources: 
- application-dev.yaml