apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: demo-app-chatbot
  janus-idp.io/tekton: demo-app-chatbot
  backstage.io/kubernetes-id: demo-app-chatbot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: demo-app-chatbot
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/